// ⚠ HCU revert risk: Sepolia enforces 20M HCU/tx + 5M depth.
// Tests passing on mock may revert here. Profile with `pnpm gas-report`.
//
// Sepolia integration test for {{NAME}} — runs under `pnpm hardhat test --network sepolia`.
// Uses @zama-fhe/relayer-sdk for real encryption + relayer-mediated user decryption.
// ethers v6 syntax only.
//
// Generated by /zama-test (zama-skills).

import { expect } from "chai";
import { ethers, network } from "hardhat";
import { createInstance, SepoliaConfig } from "@zama-fhe/relayer-sdk/node";

describe("{{NAME}} (sepolia integration)", function () {
  this.timeout(180_000); // relayer round-trips can be slow

  before(function () {
    if (network.name !== "sepolia") this.skip();
  });

  let contract: any;
  let signer: any;
  let contractAddress: string;
  let instance: Awaited<ReturnType<typeof createInstance>>;

  beforeEach(async function () {
    [signer] = await ethers.getSigners();
    const factory = await ethers.getContractFactory("{{NAME}}");
    contract = await factory.deploy();
    await contract.waitForDeployment();
    contractAddress = await contract.getAddress();
    instance = await createInstance(SepoliaConfig);
  });

  it("encrypts via relayer, calls contract, and re-decrypts the stored value", async function () {
    // 1. Build encrypted input via the real relayer SDK.
    const input = instance.createEncryptedInput(contractAddress, signer.address);
    input.add64(BigInt(123));
    const encrypted = await input.encrypt();

    // 2. State-write call.
    const tx = await contract
      .connect(signer)
      .{{WRITE_FN}}(encrypted.handles[0], encrypted.inputProof);
    await tx.wait();

    // 3. ACL re-decrypt: prove FHE.allowThis + FHE.allow(handle, signer) persisted.
    //    On Sepolia this routes through the relayer and KMS.
    const handle = await contract.{{READ_FN}}();
    const keypair = instance.generateKeypair();
    const handleContractPairs = [{ handle, contractAddress }];
    const startTimeStamp = Math.floor(Date.now() / 1000).toString();
    const durationDays = "10";
    const contractAddresses = [contractAddress];

    const eip712 = instance.createEIP712(
      keypair.publicKey,
      contractAddresses,
      startTimeStamp,
      durationDays,
    );
    const sig = await signer.signTypedData(
      eip712.domain,
      { UserDecryptRequestVerification: eip712.types.UserDecryptRequestVerification },
      eip712.message,
    );

    const result = await instance.userDecrypt(
      handleContractPairs,
      keypair.privateKey,
      keypair.publicKey,
      sig.replace("0x", ""),
      contractAddresses,
      signer.address,
      startTimeStamp,
      durationDays,
    );

    expect(BigInt(result[handle])).to.eq(BigInt(123));
  });
});
