# {{ONE_LINER}} — Design Blueprint

> Slug: `{{SLUG}}`
> Category: `{{CATEGORY}}`
> Generated by `/zama-design` on {{DATE}} — every recommendation grounded against `/zama-ai/fhevm` (1772 snippets) and `/websites/openzeppelin_confidential-contracts` (354 snippets) via context7.

## 1. Contract architecture

**Recommended base:** `{{BASE_CHOICE}}`

**Why:** {{BASE_RATIONALE}}

**Imports (Solidity):**

```solidity
{{SOL_IMPORTS}}
```

**Inheritance chain:**

```
{{INHERITANCE}}
```

## 2. Encrypted state schema

The following slots MUST stay encrypted on-chain. Plaintext addresses / counters can sit in normal `mapping`s alongside.

| Slot | Encrypted Type | Mapping Key | Purpose |
|------|----------------|-------------|---------|
{{STATE_SCHEMA_TABLE}}

**Plaintext slots (allowed):** {{PLAINTEXT_SLOTS}}

## 3. ACL strategy per actor

Every encrypted handle must be granted to (a) `address(this)` via `FHE.allowThis(handle)` immediately after assignment, and (b) every actor that will later read it via `FHE.allow(handle, actor)`. Missing grants surface as runtime ACL reverts on the relayer.

| Actor | Reads which slots | Grant pattern |
|-------|-------------------|---------------|
{{ACL_TABLE}}

> **Rule:** the contract itself ALWAYS gets `FHE.allowThis(handle)` after every encrypted write. Forgetting this is the #1 cause of "decryption fails on Sepolia but works locally" bugs. The `/zama-contract` generator injects these automatically — but document the intent here so future humans don't strip them.

## 4. Decryption path per data type

Path: **`{{DECRYPTION_PATH}}`**

| Slot | Path | Trigger | SDK call (frontend) |
|------|------|---------|---------------------|
{{DECRYPTION_TABLE}}

**Frontend SDK:** `@zama-fhe/relayer-sdk` (>= 0.4.2). The `fhevmjs` package is deprecated as of 2025-07-10 — never import it.

## 5. Key flows

{{FLOWS_BLOCK}}

## 6. Network & deployment notes

- **Network:** Sepolia testnet only (no mainnet support yet).
- **Sepolia contract addresses (ACL / KMS / Coprocessor / Confidential Token Registry):** Fetch live from `https://docs.zama.org/protocol/protocol-apps/addresses/testnet/sepolia` at deploy time. **Never pin in source.**
- **Relayer URL:** verify current value via context7 `/zama-ai/fhevm` `topic: "relayer"` before frontend init. Historically `https://relayer.testnet.zama.cloud`.
- **HCU budget:** 20M per tx, 5M depth. `/zama-contract` ships an HCU header on every generated contract; keep encrypted comparisons + branching minimal in hot paths.
- **Faucets:**
  - https://sepoliafaucet.com/ (Alchemy)
  - https://www.infura.io/faucet/sepolia (Infura)
  - https://faucet.quicknode.com/ethereum/sepolia (QuickNode)

## 7. Pinned stack (npm-registry-verified 2026-05-03)

| Package | Version | Layer |
|---------|---------|-------|
| `@fhevm/solidity` | `^0.11.1` | contracts |
| `@openzeppelin/confidential-contracts` | `^0.4.0` | contracts |
| `@openzeppelin/contracts` | `^5.6.1` | contracts (peer) |
| `@fhevm/hardhat-plugin` | `^0.4.2` | tests |
| `@zama-fhe/relayer-sdk` | `^0.4.2` (frontend); `0.4.1` (devDep) | frontend |
| `ethers` | `^6.16.0` | frontend / scripts |
| `hardhat` | `^2.28.4` | dev (NOT v3) |
| Node.js | `>=20` | runtime |

## 8. Recommended next skills

1. **`/zama-init`** — scaffold the `{{INIT_USE_CASE}}` use-case; reference this DESIGN.md while answering the prompt.
2. **`/zama-contract`** — extend the seed with the encrypted state schema in §2 (the generator wires ACL grants automatically based on §3).
3. **`/zama-test`** — generate FHE-aware mock + Sepolia tests for each ACL grant + decryption path declared above.
4. **`/zama-deploy --sepolia`** — deploy + verify (gated; requires explicit invocation).

## 9. Open questions for the developer

{{OPEN_QUESTIONS}}

---

> Companion document: [`UI-WIREFRAME.md`](./UI-WIREFRAME.md) — component tree, user flows, and the 4-state UX hook (idle / encrypting / pending / decrypted) every confidential interaction must surface.
