# {{ONE_LINER}} — UI Wireframe

> Companion to [`DESIGN.md`](./DESIGN.md). Generated by `/zama-design` on {{DATE}}.

## 1. Component tree

```
<App>
├── <Hero />                       — value prop ("{{ONE_LINER}}"), 1-screen pitch
├── <ConnectWallet />              — MetaMask + Sepolia chain check
├── <RelayerStatus />              — "FHE relayer ready" / spinner / error banner
{{COMPONENT_TREE}}
└── <Footer />                     — link to DESIGN.md, repo, audit caveat
```

**Stack:** React 18 + Vite + `ethers@^6.16.0` + `@zama-fhe/relayer-sdk@^0.4.2` + `encrypted-types@^0.0.4`.

> **Why ethers v6 (not v5, not viem):** the `@fhevm/hardhat-plugin` pins ethers v6 and the official react-template uses ethers v6 in its primary path. viem is acceptable as an alternative but has fewer Zama-ecosystem examples. **`fhevmjs` is forbidden** — deprecated 2025-07-10, replaced by `@zama-fhe/relayer-sdk`.

## 2. User flows

{{USER_FLOWS}}

## 3. The 4-state UX hook (mandatory for every encrypted interaction)

Every confidential write/read in the UI MUST surface these four states. Skipping any one of them produces "ghost transactions" where the user has no idea whether their encrypted input is in flight.

| State | Component cue | What's happening under the hood |
|-------|---------------|-------------------------------|
| `idle` | Form is enabled, button reads "Submit". | No relayer activity. |
| `encrypting` | Button reads "Encrypting…", spinner; form locked. | Relayer SDK is FHE-encrypting the input client-side. Cancellable. |
| `pending` | Button reads "Confirming on-chain…"; tx hash link visible. | Tx broadcast; waiting for inclusion + relayer indexing. |
| `decrypted` | Result rendered (or "Encrypted — only you can decrypt"). | Either user-side decryption succeeded, or oracle callback fired, or the slot is permanently encrypted to this viewer. |

**Reference hook signature** (use this exact shape for consistency across components):

```ts
type UxState = "idle" | "encrypting" | "pending" | "decrypted";

interface ConfidentialAction<T> {
  state: UxState;
  result: T | null;
  error: Error | null;
  txHash: `0x${string}` | null;
  run: (input: unknown) => Promise<void>;
  reset: () => void;
}
```

## 4. Screen states per primary view

{{SCREEN_STATES}}

## 5. Accessibility + UX guardrails

- **Disable the submit button** during `encrypting` and `pending` to prevent double-encryption (each call burns gas + relayer credits).
- **Always show the tx hash + Sepolia explorer link** during `pending` — confidential dApps already feel opaque; tx visibility offsets that.
- **Render an explicit "Encrypted — only you can decrypt this" placeholder** when a slot is encrypted to the viewer but they have not yet triggered user-side decryption. Empty state is the wrong choice here; users assume "no data."
- **Wire the RelayerStatus banner to a health-check** on app mount. If the relayer is unreachable, no encryption flow can complete — fail loud, not silently.

## 6. Out-of-scope (v1)

{{OUT_OF_SCOPE}}

## 7. Recommended next skills

1. **`/zama-frontend`** — once `/zama-init` + `/zama-contract` have produced contracts, this skill scaffolds the React app implementing the component tree above.
2. **`/zama-test`** — generate FHE-aware tests; the 4-state UX hook should be exercised in component tests too.

---

> Source of UX patterns: `@zama-fhe/relayer-sdk` README + `fhevm-react-template` (https://github.com/zama-ai/fhevm-react-template). The 4-state hook is a project convention codified by `/zama-design` to standardize encrypted-flow UX across generated dApps.
