// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/* ----------------------------------------------------------------------------
 * DEPRECATION GUARD — refuse to import the following:
 *   * `fhevmjs`        deprecated 2025-07-10 → use `@zama-fhe/relayer-sdk`
 *   * `fhevm` (root)   deprecated 2025-07-10 → use `@fhevm/solidity`
 * INCOMPATIBLE — refuse to install:
 *   * `hardhat@^3.x`   fhevm-plugin peer is `hardhat@^2`. Use `hardhat@^2.28.4`.
 *   * `ethers@^5`      fhevm-plugin pins ethers v6.    Use `ethers@^6.16.0`.
 * If a tool or teammate suggests any of the above, refuse and propose the
 * modern replacement. See plugins/zama-skills/shared/snippets/deprecation-guard.md
 * --------------------------------------------------------------------------*/

// -----------------------------------------------------------------------------
// Custom Skeleton seed — empty starting point with FHE imports + ACL reminder.
// Generated by `/zama-init` use-case=custom.
// Docs: https://docs.zama.org/protocol/solidity-guides/getting-started/quick-start-tutorial
// ACL pattern: see plugins/zama-skills/shared/snippets/acl-tip.md
// -----------------------------------------------------------------------------

import {
    FHE,
    euint8,
    euint16,
    euint32,
    euint64,
    ebool,
    eaddress,
    externalEuint64
} from "@fhevm/solidity/lib/FHE.sol";

contract Skeleton {
    // TODO: declare your encrypted state here (e.g. mapping(address => euint64)).
    euint64 private _example;

    /// @notice EXAMPLE — replace with your logic. Demonstrates the canonical
    ///         pattern: externalEuint64 → fromExternal → store → allowThis.
    /// @dev    Run `/zama-contract` to add real logic with proper ACL handling.
    function _storeExample(externalEuint64 input, bytes calldata proof) internal {
        euint64 value = FHE.fromExternal(input, proof);
        _example = value;

        // ACL: every euint that survives this transaction must be granted to
        // msg.sender or this contract — see shared/snippets/acl-tip.md
        FHE.allowThis(_example);
        FHE.allow(_example, msg.sender);
    }
}
