// Confidential dApp scaffold — generated by /zama-init.
// Use /zama-frontend (Phase 4) to wire up encryption flows with @zama-fhe/relayer-sdk.
//
// Hard rule: NEVER import the legacy frontend SDK package. Use @zama-fhe/relayer-sdk only (already in deps).
//
import { useState } from "react";

export default function App() {
  const [connected, setConnected] = useState(false);
  return (
    <main style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>Confidential Token</h1>
      <p>
        Confidential dApp scaffold. Run <code>/zama-frontend</code> in Claude Code to wire up encryption.
      </p>
      <button onClick={() => setConnected(true)}>
        {connected ? "Connected (placeholder)" : "Connect Wallet"}
      </button>
    </main>
  );
}
