// Confidential dApp scaffold — generated by /zama-init.
// Run /zama-frontend in Claude Code to wire this up with @zama-fhe/relayer-sdk
// and replace this placeholder with variant-specific panels (Mint, Balance,
// Transfer, Delegate, Votes, …) backed by encrypted handles.
//
// Hard rule: NEVER import the legacy frontend SDK package. Use @zama-fhe/relayer-sdk only.
import { Lock, Sparkles, Terminal } from "lucide-react";

export default function App() {
  return (
    <div className="min-h-screen gradient-mesh">
      <header className="border-b border-border/40 backdrop-blur-md bg-background/60 sticky top-0 z-10">
        <div className="container flex h-14 items-center justify-between">
          <div className="flex items-center gap-2 font-semibold">
            <Lock className="h-4 w-4 text-primary" />
            <span>{{USE_CASE_TITLE}} dApp</span>
          </div>
          <span className="text-xs text-muted-foreground font-mono">Sepolia · fhEVM</span>
        </div>
      </header>

      <main className="container py-12 md:py-20 animate-fade-in">
        <div className="max-w-2xl mx-auto text-center">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1 text-xs text-muted-foreground mb-6">
            <Sparkles className="h-3 w-3 text-primary" />
            Scaffolded by zama-skills
          </span>

          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-balance mb-4">
            Your <span className="text-primary">{{USE_CASE_TITLE}}</span> is ready.
          </h1>

          <p className="text-muted-foreground text-lg mb-10 text-balance">
            Contracts compile green. Frontend pipeline is plumbed. Run{" "}
            <code className="rounded bg-muted px-1.5 py-0.5 text-sm">/zama-frontend</code>{" "}
            in Claude Code to materialize the encryption flows + UI panels for this variant.
          </p>

          <div className="rounded-lg border bg-card text-left p-6 shadow-sm">
            <div className="flex items-center gap-2 text-sm font-medium mb-3">
              <Terminal className="h-4 w-4 text-primary" />
              Next step
            </div>
            <pre className="text-xs md:text-sm font-mono text-muted-foreground overflow-x-auto">
{`# In Claude Code:
/zama-frontend           # generate panels for your contract
/zama-deploy --sepolia   # deploy + verify on Sepolia
/zama-audit              # static FHE-aware safety audit`}
            </pre>
          </div>

          <p className="text-xs text-muted-foreground mt-8">
            Need to extend the contract first? Run{" "}
            <code className="rounded bg-muted px-1 py-0.5">/zama-contract</code> — it queries{" "}
            <code className="rounded bg-muted px-1 py-0.5">context7</code> live for verified ACL
            patterns.
          </p>
        </div>
      </main>
    </div>
  );
}
