// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// -----------------------------------------------------------------------------
// Confidential Voting seed — minimal encrypted-tally poll.
// Generated by `/zama-init` use-case=voting.
// Docs: https://docs.zama.org/protocol/solidity-guides/getting-started/quick-start-tutorial
//
// FALLBACK NOTE: OpenZeppelin's `VotesConfidential` is an abstract contract
// that requires `HandleAccessManager` wiring + ERC-6372 clock + voting-units
// hook (`_getVotingUnits`). For a standalone seed that compiles cleanly we
// hand-roll a minimal yes/no tally using `euint64`. Upgrade to
// `VotesConfidential` via `/zama-contract` once your token & checkpoint
// strategy are decided.
//   See: @openzeppelin/confidential-contracts/governance/utils/VotesConfidential.sol
//
// ACL pattern: see plugins/zama-skills/shared/snippets/acl-tip.md
// -----------------------------------------------------------------------------

import {FHE, euint64, externalEuint64, ebool} from "@fhevm/solidity/lib/FHE.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

contract Poll is Ownable {
    bytes32 public question;
    uint256 public endsAt;
    euint64 private yesTally;
    euint64 private noTally;
    mapping(address => bool) public hasVoted;

    event PollCreated(bytes32 question, uint256 endsAt);
    event Voted(address indexed voter);

    constructor() Ownable(msg.sender) {}

    /// @notice Owner opens a new poll. `encryptedChoice` from voters must be 0 or 1.
    function createPoll(bytes32 question_, uint256 durationSeconds) external onlyOwner {
        question = question_;
        endsAt = block.timestamp + durationSeconds;
        // Initialize tallies to encrypted zero so future FHE.add has a valid LHS.
        yesTally = FHE.asEuint64(0);
        noTally = FHE.asEuint64(0);

        // ACL: contract must retain access to its own running tallies.
        FHE.allowThis(yesTally);
        FHE.allowThis(noTally);

        emit PollCreated(question_, endsAt);
    }

    /// @notice Cast an encrypted vote. `encryptedChoice` is treated as a
    ///         euint64 in {0, 1}. A value of 1 increments yes; otherwise no.
    function vote(externalEuint64 encryptedChoice, bytes calldata inputProof) external {
        require(block.timestamp < endsAt, "Poll: closed");
        require(!hasVoted[msg.sender], "Poll: already voted");
        hasVoted[msg.sender] = true;

        euint64 choice = FHE.fromExternal(encryptedChoice, inputProof);
        ebool isYes = FHE.eq(choice, FHE.asEuint64(1));

        // Conditionally increment the right tally without revealing `choice`.
        yesTally = FHE.add(yesTally, FHE.select(isYes, FHE.asEuint64(1), FHE.asEuint64(0)));
        noTally = FHE.add(noTally, FHE.select(isYes, FHE.asEuint64(0), FHE.asEuint64(1)));

        // ACL: re-grant after every state write — see shared/snippets/acl-tip.md
        FHE.allowThis(yesTally);
        FHE.allowThis(noTally);

        emit Voted(msg.sender);
    }

    /// @notice After poll closes, owner publishes tallies for decryption.
    function publishResults() external onlyOwner {
        require(block.timestamp >= endsAt, "Poll: still open");
        // Make tallies publicly decryptable so anyone can verify the result.
        FHE.makePubliclyDecryptable(yesTally);
        FHE.makePubliclyDecryptable(noTally);
    }
}
