// Generated by /zama-frontend skill, refined with the full @zama-fhe/relayer-sdk
// userDecrypt signature.
//
// useDecrypted — React hook exposing an explicit 4-state decryption machine:
//
//   idle        no decrypt requested yet (or handle === null)
//   requesting  call sent to relayer; UI should show "awaiting relayer (5–10s on Sepolia)"
//   decrypted   plaintext available in `value`
//   error       decrypt failed; reason in `error`
//
// userDecrypt under the hood:
//   1. instance.generateKeypair()                    — ephemeral signing keypair
//   2. instance.createEIP712(...)                    — typed-data envelope to sign
//   3. walletClient.signTypedData(...)               — user EIP-712 signature
//   4. instance.userDecrypt(handleContractPairs, ...)— relayer round-trip
//
// All four steps must succeed before `decrypted`. Any throw lands in `error`.

import { useCallback, useRef, useState } from "react";
import { useAccount, useWalletClient } from "wagmi";

import { getFhevmInstance } from "@/lib/fhe";

export type DecryptStatus = "idle" | "requesting" | "decrypted" | "error";

export interface UseDecryptedReturn<T> {
  status: DecryptStatus;
  value: T | undefined;
  error: Error | undefined;
  request: () => void;
}

export interface UseDecryptedArgs {
  /** Encrypted bytes32 handle to decrypt; null disables. */
  handle: string | null;
  /** The contract that emitted the handle — required by the relayer's auth check. */
  contractAddress: `0x${string}`;
}

/**
 * useDecrypted — request a single user-decryption for an encrypted handle.
 *
 * The contractAddress is required: the relayer enforces a per-contract
 * authorization check, so the EIP-712 envelope binds the request to the
 * exact contract that emitted the handle.
 */
export function useDecrypted<T = bigint>(args: UseDecryptedArgs): UseDecryptedReturn<T> {
  const { handle, contractAddress } = args;
  const { address: userAddress } = useAccount();
  const { data: walletClient } = useWalletClient();

  const [status, setStatus] = useState<DecryptStatus>("idle");
  const [value, setValue] = useState<T | undefined>(undefined);
  const [error, setError] = useState<Error | undefined>(undefined);
  const inFlight = useRef(false);

  const request = useCallback(() => {
    if (handle === null) return;
    if (!userAddress) return;
    if (!walletClient) return;
    if (inFlight.current) return;

    inFlight.current = true;
    setStatus("requesting");
    setError(undefined);

    void (async () => {
      try {
        const instance = (await getFhevmInstance()) as unknown as {
          generateKeypair: () => { publicKey: string; privateKey: string };
          createEIP712: (
            publicKey: string,
            contractAddresses: string[],
            startTimestamp: number,
            durationDays: number,
          ) => {
            domain: Record<string, unknown>;
            types: Record<string, unknown>;
            message: Record<string, unknown>;
          };
          userDecrypt: (
            handleContractPairs: { handle: string; contractAddress: string }[],
            privateKey: string,
            publicKey: string,
            signature: string,
            contractAddresses: string[],
            userAddress: string,
            startTimestamp: number,
            durationDays: number,
          ) => Promise<Record<string, bigint | string | boolean>>;
        };

        // 1. Ephemeral keypair (per-decrypt; never persisted).
        const keypair = instance.generateKeypair();

        // 2. EIP-712 envelope: bind public key + contracts + validity window.
        // Per @zama-fhe/relayer-sdk@0.4.2 zod schema, startTimestamp + durationDays
        // are UintNumber (number), not string — older docs (and the rust SDK
        // example) showed them as string but TS validators reject string in 0.4.x.
        const startTimestamp = Math.floor(Date.now() / 1000);
        const durationDays = 10;
        const contractAddresses = [contractAddress];

        const eip712 = instance.createEIP712(
          keypair.publicKey,
          contractAddresses,
          startTimestamp,
          durationDays,
        );

        // 3. User signs the typed data with their wallet.
        // viem's WalletClient.signTypedData expects the standard EIP-712 shape.
        // We re-shape the relayer's envelope to match viem's API.
        const eip712Types = eip712.types as { [k: string]: { name: string; type: string }[] };
        const signature = await walletClient.signTypedData({
          account: userAddress,
          domain: eip712.domain as Parameters<typeof walletClient.signTypedData>[0]["domain"],
          types: {
            UserDecryptRequestVerification: eip712Types["UserDecryptRequestVerification"]!,
          },
          primaryType: "UserDecryptRequestVerification",
          message: eip712.message as Record<string, unknown>,
        });

        // 4. Relayer round-trip.
        const handleContractPairs = [{ handle, contractAddress }];
        const result = await instance.userDecrypt(
          handleContractPairs,
          keypair.privateKey,
          keypair.publicKey,
          signature.replace(/^0x/, ""),
          contractAddresses,
          userAddress,
          startTimestamp,
          durationDays,
        );

        const plain = result[handle];
        if (plain === undefined) {
          throw new Error(`[useDecrypted] relayer returned no value for handle ${handle}`);
        }
        setValue(plain as T);
        setStatus("decrypted");
      } catch (err) {
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus("error");
      } finally {
        inFlight.current = false;
      }
    })();
  }, [handle, contractAddress, userAddress, walletClient]);

  return { status, value, error, request };
}
