// Generated by /zama-frontend skill — do not edit by hand.
//
// EncryptedInput — controlled <input> that encrypts the user's number on blur
// using @zama-fhe/relayer-sdk's createEncryptedInput, then surfaces the
// resulting `{ handle, inputProof }` pair to the parent via `onEncrypted`.
//
// Bounds-checks the value against the chosen euint type before encrypting
// (T-04-24 mitigation). euint64 max = 2^64 - 1; we use BigInt to avoid
// JS Number precision loss above 2^53.
//
// Wired ABI: __CONTRACT__ — re-run /zama-frontend with --contract to swap.

import { useCallback, useState } from "react";
import { getFhevmInstance } from "@/lib/fhe";
// ABI wiring (consumed when caller composes the encrypted args into a contract write):
//   import abi from "@/abis/__CONTRACT__.json";

export type EuintType = "euint8" | "euint16" | "euint32" | "euint64";

const MAX_FOR: Record<EuintType, bigint> = {
  euint8: (1n << 8n) - 1n,
  euint16: (1n << 16n) - 1n,
  euint32: (1n << 32n) - 1n,
  euint64: (1n << 64n) - 1n,
};

export interface EncryptedInputProps {
  /** Address of the contract this encrypted input will be sent to. */
  contractAddress: `0x${string}`;
  /** Connected wallet address (the encryption is bound to this signer). */
  signerAddress: `0x${string}`;
  /** euint width — drives both bounds-check and the SDK builder method. */
  type: EuintType;
  /**
   * Called once the SDK returns `{ handles[0], inputProof }`. The caller
   * wires these as the encrypted-input args of their contract write.
   */
  onEncrypted: (out: { handle: `0x${string}`; inputProof: `0x${string}` }) => void;
  /** Optional placeholder for the input. */
  placeholder?: string;
  /** Optional className passthrough — applied to the wrapper div. */
  className?: string;
  /**
   * Optional decimals — when set, the user's typed value is multiplied by
   * 10^decimals before encryption. Lets users type "15" or "1.5" for an
   * ERC-20-style token whose on-chain unit is value * 10^decimals (raw
   * uint64). Without this, "15" gets encrypted as raw 15 and the contract
   * sees 0.000015 if it has 6 decimals.
   */
  decimals?: number;
}

type Phase = "idle" | "encrypting" | "done" | "error";

export function EncryptedInput(props: EncryptedInputProps): JSX.Element {
  const { contractAddress, signerAddress, type, onEncrypted, placeholder, className, decimals } = props;
  const [raw, setRaw] = useState<string>("");
  const [phase, setPhase] = useState<Phase>("idle");
  const [errMsg, setErrMsg] = useState<string | null>(null);

  const encrypt = useCallback(async () => {
    setErrMsg(null);
    if (raw.trim() === "") return;

    let asBig: bigint;
    try {
      // Allow decimal inputs (e.g. "15" or "1.5") when decimals prop is set;
      // require pure integer otherwise. Without scaling, "15" with a 6-decimal
      // token becomes 0.000015 — a common footgun this prop guards against.
      if (typeof decimals === "number" && decimals > 0) {
        const [intPart, fracRaw = ""] = raw.trim().split(".");
        if (!/^\d+$/.test(intPart ?? "")) throw new Error("non-numeric");
        if (fracRaw && !/^\d+$/.test(fracRaw)) throw new Error("non-numeric fraction");
        const frac = (fracRaw + "0".repeat(decimals)).slice(0, decimals);
        asBig = BigInt((intPart ?? "0") + frac);
      } else {
        asBig = BigInt(raw.trim());
      }
    } catch {
      setErrMsg(`"${raw}" is not a valid number`);
      setPhase("error");
      return;
    }
    if (asBig < 0n) {
      setErrMsg("value must be non-negative (euint types are unsigned)");
      setPhase("error");
      return;
    }
    const max = MAX_FOR[type];
    if (asBig > max) {
      setErrMsg(`value ${asBig.toString()} exceeds ${type} max (${max.toString()})`);
      setPhase("error");
      return;
    }

    setPhase("encrypting");
    try {
      const instance = await getFhevmInstance();
      // SDK surface (@zama-fhe/relayer-sdk@^0.4.2): builder pattern.
      //   instance.createEncryptedInput(contractAddress, signerAddress)
      //     .add64(value) | .add32(value) | .add16(value) | .add8(value)
      //     .encrypt() → { handles: string[], inputProof: string }
      const builder = (instance as unknown as {
        createEncryptedInput: (
          c: string,
          s: string,
        ) => {
          add8: (v: bigint) => unknown;
          add16: (v: bigint) => unknown;
          add32: (v: bigint) => unknown;
          add64: (v: bigint) => unknown;
        };
      }).createEncryptedInput(contractAddress, signerAddress);

      const adder =
        type === "euint8"
          ? (builder as { add8: (v: bigint) => { encrypt: () => Promise<{ handles: string[]; inputProof: string }> } }).add8
          : type === "euint16"
            ? (builder as { add16: (v: bigint) => { encrypt: () => Promise<{ handles: string[]; inputProof: string }> } }).add16
            : type === "euint32"
              ? (builder as { add32: (v: bigint) => { encrypt: () => Promise<{ handles: string[]; inputProof: string }> } }).add32
              : (builder as { add64: (v: bigint) => { encrypt: () => Promise<{ handles: string[]; inputProof: string }> } }).add64;

      const stage = adder.call(builder, asBig) as { encrypt: () => Promise<{ handles: unknown[]; inputProof: unknown }> };
      const out = await stage.encrypt();
      const rawHandle = out.handles[0];
      if (!rawHandle) throw new Error("relayer returned no handle");
      // SDK 0.4.x returns Uint8Array for handles[]/inputProof despite the TS
      // shape claiming string. wagmi/viem expect 0x-hex; without coercion the
      // contract write throws "e.replace is not a function" inside viem.
      const toHex = (v: unknown): `0x${string}` => {
        if (typeof v === "string") return v.startsWith("0x") ? (v as `0x${string}`) : (`0x${v}` as `0x${string}`);
        if (v instanceof Uint8Array) {
          let h = "0x";
          for (const b of v) h += b.toString(16).padStart(2, "0");
          return h as `0x${string}`;
        }
        throw new Error(`unexpected encrypt() output type: ${typeof v}`);
      };
      onEncrypted({ handle: toHex(rawHandle), inputProof: toHex(out.inputProof) });
      setPhase("done");
    } catch (err) {
      setErrMsg(err instanceof Error ? err.message : String(err));
      setPhase("error");
    }
  }, [raw, type, contractAddress, signerAddress, onEncrypted, decimals]);

  return (
    <div className={className}>
      <input
        type="text"
        inputMode="numeric"
        value={raw}
        placeholder={placeholder ?? `${type} value`}
        onChange={(e) => setRaw(e.target.value)}
        onBlur={() => {
          void encrypt();
        }}
        disabled={phase === "encrypting"}
      />
      {phase === "encrypting" && <span> encrypting…</span>}
      {phase === "done" && <span> ✓ encrypted</span>}
      {phase === "error" && errMsg && <span style={{ color: "crimson" }}> ✗ {errMsg}</span>}
    </div>
  );
}
