// Generated by /zama-frontend skill (--with-wagmi) — do not edit by hand.
//
// fhEVM relayer-sdk singleton wired against wagmi's wallet client (viem-compatible)
// rather than the EIP-1193 injected provider. Use this when your app already manages
// wallet state via wagmi.

import { initSDK, createInstance, SepoliaConfig } from "@zama-fhe/relayer-sdk/bundle";
import { useEffect, useState } from "react";
import { useWalletClient } from "wagmi";

type FhevmInstance = Awaited<ReturnType<typeof createInstance>>;

let _instance: FhevmInstance | null = null;
let _instanceChainId: number | null = null; // chain that _instance was created for
let _initInFlight: Promise<FhevmInstance> | null = null;

const SEPOLIA_CHAIN_ID = 11155111;

/**
 * getFhevmInstanceForClient — lazy singleton parameterised on a viem-compatible
 * network reference. The wagmi wallet client (`useWalletClient().data`) is
 * a viem `WalletClient`, which the relayer-sdk accepts as `network` because
 * it exposes the same `request()` JSON-RPC surface as EIP-1193 providers.
 */
export async function getFhevmInstanceForClient(
  network: unknown,
  chainId?: number,
): Promise<FhevmInstance> {
  // Cache invalidation: KMS keys + relayer URL are chain-specific. If the user
  // switched chains in the wallet between the previous init and now, the cached
  // instance is stale — drop it and re-init on the new chain.
  if (_instance && chainId !== undefined && _instanceChainId !== chainId) {
    _instance = null;
    _instanceChainId = null;
    _initInFlight = null;
  }
  if (_instance) return _instance;
  if (_initInFlight) return _initInFlight;

  if (chainId !== undefined && chainId !== SEPOLIA_CHAIN_ID) {
    console.warn(
      `[fhe-wagmi] wallet chain ${chainId} != Sepolia (${SEPOLIA_CHAIN_ID}); relayer + KMS keys will not match. ` +
        `Switch chains in the wallet and let the React tree re-render.`,
    );
  }

  if (!network) {
    throw new Error("[fhe-wagmi] no wallet client available — wait for useWalletClient().data to populate.");
  }

  _initInFlight = (async () => {
    await initSDK();
    const instance = await createInstance({
      ...SepoliaConfig,
      network,
    });
    _instance = instance;
    _instanceChainId = chainId ?? null;
    return instance;
  })();

  try {
    return await _initInFlight;
  } finally {
    _initInFlight = null;
  }
}

/**
 * useFhevmInstance — React hook returning the singleton instance once the
 * wagmi wallet client is ready. Returns `null` until init completes.
 */
export function useFhevmInstance(): FhevmInstance | null {
  const { data: walletClient } = useWalletClient();
  const [inst, setInst] = useState<FhevmInstance | null>(null);

  useEffect(() => {
    if (!walletClient) return;
    let cancelled = false;
    void getFhevmInstanceForClient(walletClient, walletClient.chain?.id).then((i) => {
      if (!cancelled) setInst(i);
    });
    return () => {
      cancelled = true;
    };
  }, [walletClient]);

  return inst;
}

/**
 * Compatibility export — matches the vanilla `getFhevmInstance()` signature.
 * Throws if no wallet client has been wired yet (wrap usages in `useFhevmInstance`
 * or pass an explicit client to `getFhevmInstanceForClient`).
 */
export async function getFhevmInstance(): Promise<FhevmInstance> {
  if (_instance) return _instance;
  throw new Error(
    "[fhe-wagmi] no cached instance — call useFhevmInstance() inside a React component first to initialise.",
  );
}

/** For tests only — drop the cached instance. */
export function __resetFhevmInstance(): void {
  _instance = null;
  _instanceChainId = null;
  _initInFlight = null;
}
