// Generated by /zama-frontend skill — do not edit by hand; re-run with --force to regenerate.
//
// fhEVM relayer-sdk singleton — uses @zama-fhe/relayer-sdk per pinned-versions.json.
// (The legacy frontend package was deprecated 2025-07-10; do not reintroduce it.)

import { initSDK, createInstance, SepoliaConfig } from "@zama-fhe/relayer-sdk/web";

declare global {
  interface Window {
    ethereum?: unknown;
  }
}

type FhevmInstance = Awaited<ReturnType<typeof createInstance>>;

let _instance: FhevmInstance | null = null;
let _initInFlight: Promise<FhevmInstance> | null = null;

const SEPOLIA_CHAIN_ID = "0xaa36a7"; // 11155111

async function detectChainId(): Promise<string | null> {
  const eth = window.ethereum as { request?: (args: { method: string }) => Promise<string> } | undefined;
  if (!eth?.request) return null;
  try {
    return await eth.request({ method: "eth_chainId" });
  } catch {
    return null;
  }
}

/**
 * getFhevmInstance — lazy singleton over relayer-sdk createInstance.
 *
 * Multiple concurrent callers share the in-flight init promise to avoid
 * double-loading the SDK wasm bundle.
 *
 * Logs a console.warn (does NOT throw) if the wallet chain isn't Sepolia
 * — the user may switch chains after page load and we don't want to
 * hard-fail rendering. The contract call itself will revert if mis-chained.
 */
export async function getFhevmInstance(): Promise<FhevmInstance> {
  if (_instance) return _instance;
  if (_initInFlight) return _initInFlight;

  _initInFlight = (async () => {
    const chainId = await detectChainId();
    if (chainId !== null && chainId !== SEPOLIA_CHAIN_ID) {
      console.warn(
        `[fhe] wallet chain ${chainId} != Sepolia (${SEPOLIA_CHAIN_ID}); relayer + KMS keys will not match. ` +
          `Switch the wallet to Sepolia and refresh.`,
      );
    }

    if (!window.ethereum) {
      throw new Error("[fhe] window.ethereum is undefined — connect a wallet (MetaMask, Rabby, …) first.");
    }

    await initSDK();
    const instance = await createInstance({
      ...SepoliaConfig,
      network: window.ethereum,
    });
    _instance = instance;
    return instance;
  })();

  try {
    return await _initInFlight;
  } finally {
    _initInFlight = null;
  }
}

/** For tests only — drop the cached instance. */
export function __resetFhevmInstance(): void {
  _instance = null;
  _initInFlight = null;
}
