// Generated by /zama-frontend skill — do not edit by hand.
//
// useDecrypted — React hook exposing an explicit 4-state decryption machine:
//
//   idle        no decrypt requested yet (or handle === null)
//   requesting  call sent to relayer; UI should show "awaiting relayer (5–10s on Sepolia)"
//   decrypted   plaintext available in `value`
//   error       decrypt failed; reason in `error`
//
// userDecrypt under the hood (per @zama-fhe/relayer-sdk@^0.4.x):
//   1. instance.generateKeypair()                    — ephemeral signing keypair
//   2. instance.createEIP712(...)                    — typed-data envelope to sign
//   3. walletClient.signTypedData(...)               — user EIP-712 signature
//   4. instance.userDecrypt(handleContractPairs, ...)— relayer round-trip
//
// IMPORTANT — failure modes documented in /zama-debug:
// - "no cached instance" → a parent component MUST call useFhevmInstance()
//   before this hook runs. Without it the no-args getFhevmInstance() throws.
// - "InvalidTypeError ... UintNumber" → startTimestamp + durationDays MUST
//   be number, not string. SDK 0.4.x zod schema rejects string.
// - "Invalid public or private key" → forgot to .replace(/^0x/, "") the
//   wallet signature before passing to relayer.

import { useCallback, useRef, useState } from "react";
import { useAccount, useWalletClient } from "wagmi";

import { getFhevmInstance } from "@/lib/fhe";

export type DecryptStatus = "idle" | "requesting" | "decrypted" | "error";

export interface UseDecryptedReturn<T> {
  status: DecryptStatus;
  value: T | undefined;
  error: Error | undefined;
  request: () => void;
}

export interface UseDecryptedArgs {
  /** Encrypted bytes32 handle to decrypt; null disables. */
  handle: string | null;
  /** Contract that emitted the handle — required by the relayer's auth check. */
  contractAddress: `0x${string}`;
}

/**
 * useDecrypted — request a single user-decryption for an encrypted handle.
 *
 * The contractAddress is required: the relayer enforces a per-contract
 * authorization check, so the EIP-712 envelope binds the request to the
 * exact contract that emitted the handle.
 */
export function useDecrypted<T = bigint>(args: UseDecryptedArgs): UseDecryptedReturn<T> {
  const { handle, contractAddress } = args;
  const { address: userAddress } = useAccount();
  const { data: walletClient } = useWalletClient();

  const [status, setStatus] = useState<DecryptStatus>("idle");
  const [value, setValue] = useState<T | undefined>(undefined);
  const [error, setError] = useState<Error | undefined>(undefined);
  const inFlight = useRef(false);

  const request = useCallback(() => {
    if (handle === null) return;
    if (!userAddress) return;
    if (!walletClient) return;
    if (inFlight.current) return;

    inFlight.current = true;
    setStatus("requesting");
    setError(undefined);

    void (async () => {
      try {
        // @zama-fhe/relayer-sdk@0.4.x ships incomplete type declarations; cast spells out
        // the methods we use. Drop this when the SDK exports proper TS types upstream.
        const instance = (await getFhevmInstance()) as unknown as {
          generateKeypair: () => { publicKey: string; privateKey: string };
          createEIP712: (
            publicKey: string,
            contractAddresses: string[],
            startTimestamp: number,
            durationDays: number,
          ) => {
            domain: Record<string, unknown>;
            types: Record<string, unknown>;
            message: Record<string, unknown>;
          };
          userDecrypt: (
            handleContractPairs: { handle: string; contractAddress: string }[],
            privateKey: string,
            publicKey: string,
            signature: string,
            contractAddresses: string[],
            userAddress: string,
            startTimestamp: number,
            durationDays: number,
          ) => Promise<Record<string, bigint | string | boolean>>;
        };

        // 1. Ephemeral keypair (per-decrypt; never persisted).
        const keypair = instance.generateKeypair();

        // 2. EIP-712 envelope: bind public key + contracts + validity window.
        const startTimestamp = Math.floor(Date.now() / 1000);
        const durationDays = 10;
        const contractAddresses = [contractAddress];

        const eip712 = instance.createEIP712(
          keypair.publicKey,
          contractAddresses,
          startTimestamp,
          durationDays,
        );

        // 3. User signs the typed data with their wallet (viem WalletClient).
        const eip712Types = eip712.types as { [k: string]: { name: string; type: string }[] };
        const signature = await walletClient.signTypedData({
          account: userAddress,
          domain: eip712.domain as Parameters<typeof walletClient.signTypedData>[0]["domain"],
          types: {
            UserDecryptRequestVerification: eip712Types["UserDecryptRequestVerification"]!,
          },
          primaryType: "UserDecryptRequestVerification",
          message: eip712.message as Record<string, unknown>,
        });

        // 4. Relayer round-trip. signature MUST be stripped of '0x'.
        const handleContractPairs = [{ handle, contractAddress }];
        const result = await instance.userDecrypt(
          handleContractPairs,
          keypair.privateKey,
          keypair.publicKey,
          signature.replace(/^0x/, ""),
          contractAddresses,
          userAddress,
          startTimestamp,
          durationDays,
        );

        const plain = result[handle];
        if (plain === undefined) {
          throw new Error(`[useDecrypted] relayer returned no value for handle ${handle}`);
        }
        setValue(plain as T);
        setStatus("decrypted");
      } catch (err) {
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus("error");
      } finally {
        inFlight.current = false;
      }
    })();
  }, [handle, contractAddress, userAddress, walletClient]);

  return { status, value, error, request };
}
