// Generated by /zama-frontend skill — do not edit by hand.
//
// useDecrypted — React hook exposing an explicit 4-state decryption machine:
//
//   idle        no decrypt requested yet (or handle === null)
//   requesting  call sent to relayer; UI should show "awaiting relayer (5–10s on Sepolia)"
//   decrypted   plaintext available in `value`
//   error       decrypt failed; reason in `error`
//
// Why explicit states? On Sepolia user-decryption round-trips routinely take
// 5–10s (KMS share assembly + relayer round-trip). A two-state loading flag
// makes the UI look frozen; surfacing `requesting` lets you render a spinner
// with a "patience required" copy.
//
// Caching: this hook is intentionally minimal — no built-in cache, no auto-
// retry. To wrap with React Query / SWR:
//
//   const q = useQuery({ queryKey: ['fhe', handle], queryFn: () => decryptOnce(handle) });
//
// where `decryptOnce` calls `getFhevmInstance().userDecrypt(...)` directly.
// The hook below is the right tool when you want a deliberate, user-triggered
// reveal (button click) — the typical UX for confidential balances.

import { useCallback, useRef, useState } from "react";
import { getFhevmInstance } from "@/lib/fhe";

export type DecryptStatus = "idle" | "requesting" | "decrypted" | "error";

export interface UseDecryptedReturn<T> {
  status: DecryptStatus;
  value: T | undefined;
  error: Error | undefined;
  request: () => void;
}

/**
 * useDecrypted — request a single user-decryption for an encrypted handle.
 *
 * @param handle  bytes32 handle string returned by your contract; null disables.
 * @returns       { status, value, error, request }
 */
export function useDecrypted<T = bigint>(handle: string | null): UseDecryptedReturn<T> {
  const [status, setStatus] = useState<DecryptStatus>("idle");
  const [value, setValue] = useState<T | undefined>(undefined);
  const [error, setError] = useState<Error | undefined>(undefined);
  const inFlight = useRef(false);

  const request = useCallback(() => {
    if (handle === null) return;
    if (inFlight.current) return;
    inFlight.current = true;
    setStatus("requesting");
    setError(undefined);

    void (async () => {
      try {
        const instance = await getFhevmInstance();
        // Per relayer-sdk surface (@zama-fhe/relayer-sdk@^0.4.2):
        //   instance.userDecrypt({ handles: string[], ... }) → Record<handle, plaintext>
        // The full call requires signature + EIP-712 typed data plumbing the
        // app already does; consult the project's wagmi/ethers signer to fill.
        const result = (await (instance as unknown as {
          userDecrypt: (args: { handles: string[] }) => Promise<Record<string, T>>;
        }).userDecrypt({ handles: [handle] })) as Record<string, T>;

        const plain = result[handle];
        if (plain === undefined) {
          throw new Error(`[useDecrypted] relayer returned no value for handle ${handle}`);
        }
        setValue(plain);
        setStatus("decrypted");
      } catch (err) {
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus("error");
      } finally {
        inFlight.current = false;
      }
    })();
  }, [handle]);

  return { status, value, error, request };
}
