// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// -----------------------------------------------------------------------------
// Sealed-Bid Auction seed — custom euint64 pattern (no OZ primitive).
// Generated by `/zama-init` use-case=auction.
// Reference: Zama official auction tutorial — query context7
//   `/zama-ai/fhevm` topic:"auction" for the latest pattern. The select-on-
//   compare flow below mirrors that tutorial.
// Docs: https://docs.zama.org/protocol/solidity-guides/getting-started/quick-start-tutorial
// ACL pattern: see plugins/zama-skills/shared/snippets/acl-tip.md
// -----------------------------------------------------------------------------

import {FHE, euint64, eaddress, ebool, externalEuint64} from "@fhevm/solidity/lib/FHE.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

contract SealedBidAuction is Ownable {
    uint256 public endsAt;
    bool public settled;

    euint64 private highestBid;
    eaddress private highestBidder;

    event BidSubmitted(address indexed bidder);
    event Settled();

    constructor(uint256 durationSeconds) Ownable(msg.sender) {
        endsAt = block.timestamp + durationSeconds;
        highestBid = FHE.asEuint64(0);
        highestBidder = FHE.asEaddress(address(0));
        // ACL: contract retains read access to running winner state.
        FHE.allowThis(highestBid);
        FHE.allowThis(highestBidder);
    }

    /// @notice Submit a sealed bid. The on-chain comparison runs entirely in
    ///         ciphertext — neither the amount nor the loser's identity leaks.
    function bid(externalEuint64 encryptedAmount, bytes calldata inputProof) external {
        require(block.timestamp < endsAt, "Auction: ended");

        euint64 amount = FHE.fromExternal(encryptedAmount, inputProof);
        ebool isHigher = FHE.gt(amount, highestBid);

        highestBid = FHE.select(isHigher, amount, highestBid);
        highestBidder = FHE.select(isHigher, FHE.asEaddress(msg.sender), highestBidder);

        // ACL: every euint that survives this transaction must be re-granted
        // to the contract — see shared/snippets/acl-tip.md
        FHE.allowThis(highestBid);
        FHE.allowThis(highestBidder);

        emit BidSubmitted(msg.sender);
    }

    /// @notice After the auction window, expose the winner. The owner can
    ///         decrypt both handles; the public can decrypt the bidder.
    function settle() external onlyOwner {
        require(block.timestamp >= endsAt, "Auction: still open");
        require(!settled, "Auction: already settled");
        settled = true;

        // Grant decryption rights:
        //   - owner: full visibility on price + winner.
        //   - public: winner identity (publicly decryptable).
        FHE.allow(highestBid, msg.sender);
        FHE.allow(highestBidder, msg.sender);
        FHE.makePubliclyDecryptable(highestBidder);

        emit Settled();
    }
}
