// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// -----------------------------------------------------------------------------
// Confidential Token seed (ERC-7984 + ERC20 wrapper)
// Generated by `/zama-init` use-case=confidential-token.
// Docs: https://docs.zama.org/protocol/solidity-guides/getting-started/quick-start-tutorial
// Registry: registration with the Confidential Token Registry on Sepolia is
//           DEFERRED to `/zama-deploy` (see ./scripts/register-token.ts).
// ACL pattern: see plugins/zama-skills/shared/snippets/acl-tip.md
// -----------------------------------------------------------------------------

import {FHE, euint64, externalEuint64} from "@fhevm/solidity/lib/FHE.sol";
import {ERC7984ERC20Wrapper} from "@openzeppelin/confidential-contracts/token/ERC7984/extensions/ERC7984ERC20Wrapper.sol";
import {ERC7984} from "@openzeppelin/confidential-contracts/token/ERC7984/ERC7984.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/// @title  Token — confidential ERC-7984 wrapper around an existing ERC-20.
/// @notice Minimum-viable demo: owner can wrap underlying ERC-20 into confidential
///         balances and demo-mint a trivial encrypted amount to themselves.
///         Replace with your real economics via `/zama-contract`.
contract Token is ERC7984ERC20Wrapper, Ownable {
    constructor(IERC20 underlying_, string memory name_, string memory symbol_, string memory contractURI_)
        ERC7984(name_, symbol_, contractURI_)
        ERC7984ERC20Wrapper(underlying_)
        Ownable(msg.sender)
    {}

    /// @notice Demo-mint a confidential amount to the caller. Replace with your
    ///         real mint authorization (e.g. role-gated, oracle-fed, etc.).
    /// @param  encryptedAmount externally-encrypted euint64 amount.
    /// @param  inputProof      relayer-issued attestation for `encryptedAmount`.
    function mintConfidential(externalEuint64 encryptedAmount, bytes calldata inputProof) external onlyOwner {
        euint64 amount = FHE.fromExternal(encryptedAmount, inputProof);

        // ACL: every euint that survives this transaction must be granted to
        // msg.sender or this contract — see shared/snippets/acl-tip.md
        FHE.allowThis(amount);
        FHE.allow(amount, msg.sender);

        _mint(msg.sender, amount);
    }
}
