// Generated by /zama-frontend skill — do not edit by hand.
// Re-run /zama-frontend with --contract <Name> to regenerate after changing
// contracts. Variant detected: {{VARIANT}}.

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider, useAccount, useChainId } from "wagmi";
import { sepolia } from "wagmi/chains";
import { Loader2 } from "lucide-react";

import abiJson from "@/abis/{{CONTRACT}}.json";
import { wagmiConfig } from "./wagmi";
import { Header } from "@/ui/Header";
import { Card, CardContent } from "@/ui/Card";
{{PANEL_IMPORTS}}

const CONTRACT_ADDRESS = "{{CONTRACT_ADDRESS}}" as const;
const ABI = (abiJson as { abi: readonly unknown[] }).abi;
const TITLE = "{{USE_CASE_TITLE}}";

const queryClient = new QueryClient();

export default function App(): JSX.Element {
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <Shell />
      </QueryClientProvider>
    </WagmiProvider>
  );
}

function Shell(): JSX.Element {
  return (
    <div className="min-h-screen gradient-mesh">
      <Header title={TITLE} contractAddress={CONTRACT_ADDRESS} />
      <main className="container py-8 md:py-12 animate-fade-in">
        <ConnectedView />
      </main>
    </div>
  );
}

function ConnectedView(): JSX.Element {
  const { isConnected, address } = useAccount();
  const chainId = useChainId();

  if (!isConnected || !address) {
    return (
      <div className="max-w-md mx-auto text-center pt-8">
        <Card>
          <CardContent className="pt-6 space-y-2">
            <Loader2 className="h-6 w-6 mx-auto text-muted-foreground animate-spin" />
            <p className="text-sm text-muted-foreground">
              Connect your wallet to get started — top-right corner.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (chainId !== sepolia.id) {
    return (
      <div className="max-w-md mx-auto text-center pt-8">
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm">Switch to Sepolia to continue (top-right "Switch" button).</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="grid gap-4 md:gap-6 max-w-2xl mx-auto">
      {{PANEL_RENDER}}
    </div>
  );
}
