# {{USE_CASE_TITLE}} — Confidential dApp

> Scaffolded by [`zama-skills`](https://github.com/zama-ai/zama-skills) — `/zama-init` in Claude Code.

## 30-second value prop

This project is a **confidential dApp** running on Sepolia testnet using Zama Protocol's fhEVM (fully homomorphic encryption on Ethereum). Every dependency was pinned from `shared/pinned-versions.json` and **verified live via context7** at scaffold time — no hallucinated APIs, no deprecated packages. You get a working pnpm monorepo with:

- `packages/contracts/` — Hardhat + `@fhevm/solidity` + OpenZeppelin Confidential Contracts, ready to compile
- `packages/frontend/` — Vite + React 18 + ethers v6 + `@zama-fhe/relayer-sdk` (the official SDK; the legacy SDK package is **deprecated** and never imported)
- `.env.example` + Sepolia onboarding (faucets, MetaMask deep-link)

You can be reading encrypted state from a deployed Sepolia contract in under 30 minutes from `pnpm install`.

## Quick start

```bash
pnpm install                          # install all workspace deps
cp .env.example .env                  # then fill in INFURA_API_KEY, MNEMONIC, ETHERSCAN_API_KEY
pnpm compile                          # compile contracts (already verified green at scaffold time)
pnpm test                             # run Hardhat tests with the fhEVM mock plugin
pnpm dev:frontend                     # launch the Vite dev server on http://localhost:5173
```

## Configure Sepolia in MetaMask

Open MetaMask → Networks → "Add a network" → use this deep-link:

- <https://chainid.network/?search=sepolia> — clickable; MetaMask handles the network add for you.

Alternatively: <https://chainlist.org/chain/11155111>.

## Get testnet ETH (Sepolia faucets)

Pick whichever responds fastest — they all work:

- <https://sepoliafaucet.com/> — Alchemy (no signup, signs in with Alchemy account)
- <https://www.infura.io/faucet/sepolia> — Infura (requires Infura account)
- <https://faucet.quicknode.com/ethereum/sepolia> — QuickNode

You only need ~0.05 ETH to deploy + run tests.

## Pinned versions

Every dependency in `package.json` was resolved at scaffold time from a curated `pinned-versions.json` and cross-checked against context7's `/zama-ai/fhevm` source. The Sepolia contract addresses (ACL / KMS / Coprocessor / Confidential Token Registry) are **never hardcoded** — fetch them live from:

- <https://docs.zama.org/protocol/protocol-apps/addresses/testnet/sepolia>

## Mnemonic safety

> **TEST MNEMONIC ONLY — never use a mainnet wallet's seed phrase in `.env`.**

Generate a fresh BIP-39 phrase from MetaMask (create a new wallet) or via `npx @scure/bip39 generate`. The `.env` file is in `.gitignore`; commit `.env.example` only.

## Next steps in Claude Code

After your contracts compile and you've funded the deployer wallet:

- `/zama-contract` — extend / author confidential contracts with verified ACL patterns
- `/zama-test` — generate fhEVM-aware tests (encrypted inputs, decrypt assertions)
- `/zama-deploy --sepolia` — deploy + verify on Etherscan, register with the Confidential Token Registry if applicable
- `/zama-frontend` — wire the Vite frontend to the relayer SDK for end-to-end encryption flows

## Learning resources

- Zama protocol docs: <https://docs.zama.org/protocol>
- fhEVM Solidity guide: <https://docs.zama.org/protocol/solidity-guides/getting-started/quick-start-tutorial>
- OpenZeppelin Confidential Contracts: <https://github.com/OpenZeppelin/openzeppelin-confidential-contracts>

---

*Generated by [zama-skills](https://github.com/zama-ai/zama-skills). Do not commit `.env`.*
