// Mock unit test for Token — runs under `pnpm hardhat test` (default network).
// Exercises @fhevm/hardhat-plugin encrypted-input mock + decrypt assertion + ACL re-decrypt.
//
// Generated by /zama-test (zama-skills). ethers v6 syntax only.

import { expect } from "chai";
import { ethers, fhevm } from "hardhat";
import { FhevmType } from "@fhevm/mock-utils";

describe("Token (mock)", function () {
  let contract: any;
  let signer: any;
  let contractAddress: string;

  beforeEach(async function () {
    [signer] = await ethers.getSigners();
    const factory = await ethers.getContractFactory("Token");
    contract = await factory.deploy();
    await contract.waitForDeployment();
    contractAddress = await contract.getAddress();
  });

  it("accepts encrypted input via mock and stores it", async function () {
    // 1. Build the encrypted input (mock).
    const input = fhevm.createEncryptedInput(contractAddress, signer.address);
    input.add64(42n);
    const encrypted = await input.encrypt();

    // 2. Call the state-write function.
    await contract.connect(signer).TODO_writeFn(encrypted.handles[0], encrypted.inputProof);

    // 3. Decrypt the stored handle and assert value matches.
    const handle = await contract.TODO_readFn();
    const clear = await fhevm.userDecryptEuint(FhevmType.euint64, handle, signer);
    expect(clear).to.eq(42n);
  });

  it("ACL re-decrypt assertion: handle remains decryptable by signer after state-write", async function () {
    // This test catches missing FHE.allowThis(handle) or FHE.allow(handle, signer).
    // If either ACL grant is absent in the contract, the userDecryptEuint call below throws.
    const input = fhevm.createEncryptedInput(contractAddress, signer.address);
    input.add64(7n);
    const encrypted = await input.encrypt();
    await contract.connect(signer).TODO_writeFn(encrypted.handles[0], encrypted.inputProof);

    // Re-decrypt from the same signer context — proves ACL grants persist.
    const reDecrypt = await fhevm.userDecryptEuint(
      FhevmType.euint64,
      await contract.TODO_readFn(),
      signer,
    );
    expect(reDecrypt).to.eq(7n);
  });
});
